from diffusers.models import AutoencoderKL
from diffusers import StableDiffusionPipeline
import torch
import numpy as np
import os

promptsub = {
    "*epic*": "Epic Realistic, high Quality, masterpiece, neutral colors, screen space refractions, (intricate details, hyperdetailed:1.2), artstation, complex background",
}



promptdict = {
    "city": "an bird-eye view of a cyberpunk city",
    "cybercity": "bird-eye view of a cyberpunk city, epic realistic, (hdr:1.4), (muted colors:1.4), apocalypse, abandoned, screen space refractions, (intricate details), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background, buildings",
    "cybercity2": "bird-eye view of a cyberpunk city, epic realistic, (hdr:1.4), apocalypse, abandoned, screen space refractions, (intricate details), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background, buildings, masterpiece",
    "cyberalley": "cyberpunk city alley, epic realistic, (hdr:1.4), (muted colors:1.1), apocalypse, abandoned, screen space refractions, (intricate details), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "robot": "a robot playing drums in a rock concert",
    "alpine_pr": "Alpine valley landscape, photorealistic",
    "alpine_hq": "Alpine valley landscape, high quality",
    "alpine": "Alpine valley landscape",
    "alpine_gpt2": "a high-quality photo of an alpine valley, Resolution, 3000 pixels or higher. Valley, prominently centered, gentle slope, lush vegetation. Mountains, Towering, snow-capped, contrasting the valley. Lighting, Natural, clear blue sky, softsunlight. Colors, Vibrant and true to life. Focus, Sharp throughout, capturing fine details. Composition, Depth and scale, emphasizing grandeur",
    "sunset": "a sunset over a lake, masterpiece, water reflection , epic realistic, (hdr:1.4), (colorful:1.4), screen space refractions, (intricate details), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background, red, emphasizing grandeur",
    "mountain": "a mountain in barren, desert enviroment. Epic realistic, masterpiece, detailed, rocky, interesting topology",
    "sand2": "an intimidating sandy mountain in barren, desert enviroment. Epic realistic, steep, high quality masterpiece, detailed, with interesting topology",
    "sand^": "an intimidating sandy mountain in barren, desert enviroment. Arrows pointing upward. Epic realistic, steep, high quality masterpiece, detailed, with interesting topology",
    "factorio": "A port view of a modern city integrated with a production assembly line. Epic Realistic. High Quality, masterpiece, Hyper detailed. Include Conveyor Belt and buildings",
    "market": "An Urban marketplace where good are transported by conveyor belts from distant production line. High Quality, masterpiece, (intricate details, hyperdetailed:1.2), artstation, complex background",
    "market2": "An Urban marketplace where good are transported by conveyor belts from distant production line. Epic Realistic, neutral colors, night, screen space refractions, (intricate details, hyperdetailed:1.2), artstation, cinematic shot, vignette, complex background",
    "market3": "An Urban marketplace where good are transported by conveyor belts from distant production line. Epic Realistic, high Quality, masterpiece, neutral colors, screen space refractions, (intricate details, hyperdetailed:1.2), artstation, complex background",
    "classroom": "Classroom of the future. Aritifical Intelligence based education. Epic Realistic, high Quality, masterpiece, neutral colors, screen space refractions, (intricate details, hyperdetailed:1.2), artstation, complex background",
    "education": "Futuristic State of Education. Epic Realistic, Electric, High Quality, masterpiece, neutral colors, screen space refractions, (intricate details, hyperdetailed:1.2), artstation, complex background, diverse",
    "oil": "An oil painting of a relaxing, beautiful park, featuring a bench, colorful trees and a lake. High Quality, masterpiece, screen space refractions, (intricate details, hyperdetailed:1.2), artstation, complex background",
    "park": "Beautiful park, featuring a bench, colorful trees and a lake. High Quality, masterpiece, screen space refractions, (intricate details, hyperdetailed:1.2), artstation, complex background",
    "park2": "Beautiful park, featuring a bench, animals, colorful trees and a river. High Quality, masterpiece, screen space refractions, (intricate details, hyperdetailed:1.2), artstation, complex background",
    "underground": "A huge underground city, made from metal and clay, partially flooded. High Quality, masterpiece, screen space refractions, (intricate details, hyperdetailed:1.2), artstation, complex background",
    "fat": " oil painting with heavy impasto of a fat man on a canvas, cosmic horror painting, elegant intricate artstation concept art by craig mullins, (intricate details, hyperdetailed:1.4)",
    "fat2": " oil painting with heavy impasto of a fat man on a canvas. High Quality, masterpiece. elegant intricate artstation concept art by craig mullins, (intricate details, hyperdetailed:1.4)",
    "ship1": "a detailed oil painting of a wooden ship, with monster in the water. masterpiece. (hyperdetailed:1.2), artstation.",
    "ship2": "a bench on a deck of wooden ship. A Kraken in the water with tentacles. Cosmic Horror. Detailed oil painting, masterpiece. (hyperdetailed:1.2), artstation.",
    "bench": "a bench in a park. Colorful Trees. Detailed oil painting by Leonid Afremov. masterpiece, artstation.",
    "bench2": "a bench and a couple with umbrella in a park. Colorful Trees. Detailed oil painting by Leonid Afremov. masterpiece, artstation.",
    "elephant": "A sureal painting of a pack of colorful hindo elephants stopping to pump in a gas station. Strong color (hdr:1.4), (colorful:1.7), screen space refractions, (intricate details, hyperdetailed:1.2), artstation, vignette, complex background with buildings.",
    "astroid": "A large astroid mining station attacked by a giant alien. Cosmic Horror. Epic Realistic, masterpiece,  (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "space": "In space, a large space station on small astroid attacked by a lovecraftian monster. Cosmic Horror. Epic Realistic, masterpiece,  (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background with red and blue stars",
    "village": "A mysterious medieval village in the woods, occupied by fancy robots. Epic Realistic, masterpiece, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background with myst",
    "opera": "An bizzare opera performance in sunken london. Cosmic Horror themes. Epic Realistic, masterpiece, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "ants": "The inside of an any colony overflown with lava. The ants are evacuating . Epic Realistic, masterpiece, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "zerg": "A zerg assualt on terrans in a frozen planet, warhammer 2K. Epic Realistic, masterpiece, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex icy background",
    "dragon": "A dragon stabbed by arrows, flying in a blizzard storm. Epic Realistic, masterpiece, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex icy background",
    "president": "Robot wearing a writer hat fighting a robot wearing a painter hat in an MMA arena. Epic Realistic, masterpiece, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex icy background",
    "morgana": "A paradise on a floating island, in the middle of dark, horrifying space. Cosmic Horror. Epic Realistic, masterpiece, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "morgana2": "A shiny, colorful paradise on a floating island, in the middle of dark, horrifying void. Epic Realistic, masterpiece, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "morgana3": "A sunlit paradise on a floating island, in the middle of dark, destructive void. Epic Realistic, masterpiece, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "island": "A sunlit paradise on a floating island, in the middle of dark, destructive void. Epic Realistic, masterpiece, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background with metallic scraps",
    "blighttown": "blighttown, a dark horrifying ruins in the middle of a toxic swamp. Cosmic Horror. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "clancy": "Sam fisher infiltrating a covert facility. Pandora tomorrow. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "melting": "A melting steampunk city. Gigantic, hot, melting structures. Surealistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background with buildings",
    "ecolony": "A colony of monkeys inside an computer chip. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "crater": " A huge crater in the middle of a modern city, with cycling helicopters. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "crater2": " A huge crater in the middle of a modern city. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "crater3": " A huge crater in the middle of a paris, french. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "invasion": "Alien invasion of Jerusalem, Israel. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.3), artstation, vignette, complex background",
    "intrigue": "A portrait of a person. The image sybmolizes intrigue, mystery, and search for knowledge. Epic, Photo Realistic, (hdr:1.2), (intricate details, hyperdetailed:1.2), artstation",
    "resignation": "A portrait of a person, Symbolizing the happiness in resignation. Epic, Photo Realistic, (hdr:1.2), (intricate details, hyperdetailed:1.2), artstation",
    "resignation2": "A full body image of a person, Symbolizing the happiness in resignation. Epic, Photo Realistic, (hdr:1.2), (intricate details, hyperdetailed:1.2), artstation",
    "house": "A floating house being sucked into a black hole. Epic, Photo Realistic, (hdr:1.2), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "house2": "A floating house being sucked into a black hole, falling apart. Epic, Photo Realistic, (hdr:1.2), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background with debris",
    "demon": "A cat stroking a demon's head, in a throne room. Epic, Photo Realistic, (hdr:1.2), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "spikes": "The hollow knight traversing the spiky queen's garden. Epic, Photo Realistic, (hdr:1.2), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",    
    "twin": "The ash twin planet, from the outer wilds. Epic, Photo Realistic, (hdr:1.2), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",    
    "moon": "The quantum moon. Epic, Photo Realistic, (hdr:1.2), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",    
    "tree": "bird-eye view of a cyberpunk city covered in roots of a gigantic tree. epic realistic, (hdr:1.4), (muted colors:1.4), apocalypse, abandoned, screen space refractions, (intricate details), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background, buildings",    
    "roots": "Roots covering a cyberpunk city. Epic realistic, bird-eye, (hdr:1.4), (muted colors:1.4), apocalypse, abandoned, screen space refractions, (intricate details), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background with buildings and a giant tree",    
    "ship3": "A ship dodging and monster in the water. Cosmic Horror. Detailed oil painting by Leonid Afremov. masterpiece, artstation. (hdr:1.4), (intricate details, hyperdetailed:1.2), vignette, complex background",
    "ship4": "Detailed liquid oil painting of a missle boat by William Blake. Charcoal sketch, masterpiece, artstation. (hdr:1.4), (intricate details, hyperdetailed:1.2), vignette, complex background with an aircraft carrier",
    "ship5": "Detailed liquid oil painting of a missle boat. Realism, Impressionism, masterpiece, artstation. (hdr:1.4), (intricate details, hyperdetailed:1.2), vignette, complex background with an aircraft carrier",
    "ship6": "Detailed liquid oil painting saar 3 class missle-boat. Impressionism, masterpiece, artstation. (hdr:1.4), (intricate details, hyperdetailed:1.2), vignette, complex background with an aircraft carrier",
    "ship7": "Detailed liquid oil painting of a missle-boat. Impressionism, masterpiece, artstation. (hdr:1.4), (intricate details, hyperdetailed:1.2), vignette, complex background with explosions",
    "ship8": "Detailed liquid oil painting of a missle boat. Impressionism, masterpiece, artstation. (hdr:1.4), (intricate details, hyperdetailed:1.2), vignette, complex background with nightmarish skies",
    "ship9": "Detailed liquid oil painting of a missle boat with sails. Realism, Impressionism, masterpiece, artstation. (hdr:1.4), (intricate details, hyperdetailed:1.2), vignette, complex background with an aircraft carrier",
    "ship10": "Detailed liquid oil painting of a missle boat. Mysterious skies. Realism, Impressionism, masterpiece, artstation. (hdr:1.4), (intricate details, hyperdetailed:1.2), vignette, complex background with an oil rig",
    "rig": "An oil rig floating in space. Masterpiece, artstation. (hdr:1.2), (intricate details, hyperdetailed:1.2), vignette, complex background",
    "birthday": "A birthday cake and baloons, during the final exams period. Epic, Photo Realistic, (hdr:1.2), (intricate details, hyperdetailed:1.2), vignette, complex background",
    "birthday2": "A tired girl studying for final exams over a birthday cake. Epic, Photo Realistic, (hdr:1.2), (intricate details, hyperdetailed:1.2), vignette, complex background",
    "birthday3": "A girl sleeping on a birthday cake, with scattered notebooks. Epic, Photo Realistic, (hdr:1.2), (intricate details, hyperdetailed:1.2), vignette, complex background",
    "radioactive": "A radioactive man fighting a burning monster. Epic, Photo Realistic, (hdr:1.2), (intricate details, hyperdetailed:1.2), vignette, complex urban background, filled with destruction.",
    "nature": "bird-eye view of a cyberpunk city claimed by nature. epic realistic, (hdr:1.4), (muted colors:1.4), apocalypse, abandoned, screen space refractions, (intricate details), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background with building a single giant tree",
    "worldend": "A beautiful tropic beach at world's end with palm trees, made out metal and electricity. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "worldend2": "A beautiful tropic beach at world's end, made out metal and electricity. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "pinguin": "A pinguin ringing an alarm bell. Cute, Cartoonish, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette.",
    "prow": "Prow of a wooden ship that sank in the depths of the sea. an astronaut swimming in the water with life rope. Cosmic Horror. Detailed oil painting, masterpiece. (hyperdetailed:1.2), artstation.",
    "isometric": "Isometric view of a cyberpunk city, epic realistic, (hdr:1.4), (muted colors:1.4), apocalypse, abandoned, screen space refractions, (intricate details), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background, buildings",
    "melting2": "A steampunk city, with melting wax buildings. Gigantic, Surealistic, photorealistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background with pipes and cogs",
    "oasis": "A beautiful oasis in the middle of the endless void. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "hollow": "The giant, subterrean, gate to hollow earth. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "borabora": "Detailed liquid oil painting of Bora Bora. Tropical, Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "skylava": "A rodden infested countryside with purple lava sky and lightnings. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "elevator": "The basis of a space elevator. Hot colors, Grandiose. Epic Realistic, (hdr:1.6), (intricate details, hyperdetailed:1.3), artstation, vignette, complex background",
    "mordorail": "An aerial lift or monorail over the fiery pits of mordor. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "mordor": "A cable car over the fiery pits of mordor. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "gunfight": "Armed beaver people fighting armed fox people in a urban gang warfare. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette.",
    "southpark": "A southpark style drawing of a cyberpunk city. Cartoonish, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette.",
    "magical-cartoon": "A magical fantasy kingdom with colorful mushrooms and giant shoes. Cartoonish, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette.",
    "magical-real": "A magical fantasy kingdom with colorful mushrooms and giant shoes. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette.",
    "magical-oil": "A magical fantasy kingdom with colorful mushrooms and giant shoes. Detailed oil painting, masterpiece. (hyperdetailed:1.2), artstation.",
    "magical-sureal": "A magical fantasy kingdom with colorful mushrooms and giant shoes. Gigantic, Surealistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette",
    "waterfall": "Gravity defying waterfalls in a magical fantasy kingdom. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette. Complex background with floating islands",
    "waterfall-cartoon": "A cartoon of a Gravity defying waterfalls in a magical fantasy kingdom. (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette. Complex background with floating islands",
    "waterfall-oil": "A canvas oil painting of  a Gravity defying waterfalls in a magical fantasy kingdom. (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette. Complex background with floating islands",
    "waterfall-real": "A photorealistic painting of a Gravity defying waterfalls in a magical fantasy kingdom. (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette. Complex background with floating islands",
    "voxel-city": "voxel art of a stunning panorama of neo-city, a futuristic cyberpunk city adorned with neon buildings and technology, cyberpunk art, trending on ArtStation",
    "voxel-city-real": "voxel art of a stunning panorama of neo-city, a futuristic cyberpunk city adorned with neon buildings and technology. Epic Realistic (hdr:1.4), cyberpunk art, trending on ArtStation",
    "melting3": "Melting wax. Steampunk, Gigantic, Surealistic, photorealistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background with pipes and cogs",
    "logo": "A logo for DS, in the Technion. Theory, Deep learning, Artificial intelligence, Quantization, Optimization. Original, Creative, masterpiece, Inspiring",
    "logo2": "A logo with neural networks spelling the letters D and S. Theory, Deep learning, Artificial intelligence, Quantization, Optimization. Original, Creative, masterpiece, Inspiring",
    "robrob": "A futuristic factory, with robots building robots. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "robrob2": "A futuristic factory, in open space near a coast, with robots building robots. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background with a sunset",
    "cave": "An ancient library inside a cave. With waterfall, bookshelves, and stalactites. Mysterious, Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "pigs0": "A normandy style invasion of pigs on Gaza bearch. Destruction, War. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "pigs1": "Pigs on Normandy amphibious landers, arriving to Gaza's shore. Destruction, War. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "pigs2": "Pigs sailing on amphibious landers, invading a arabic port. (Destruction:0.7) Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "pigs3": "Pigs on LCVP Higgins boats, invading an Gaza's beach. (Destruction:0.7) Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "pigs4": "Invasion of pigs on Gaza shore, with WW2 Landing Craft, Vehicle Personnel. Destruction, War. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "boar0": "A normandy style invasion of boars on Gaza bearch. Destruction, War. Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "boar2": "Boars on WW2 landing boats, invading an Gaza shore. (Destruction:0.7) Epic Realistic, (hdr:1.4), (intricate details, hyperdetailed:1.2), artstation, vignette, complex background",
    "lion": "A majestic lion jumping from a big stone at night, with star-filled skies. Hyperdetailed, with Complex tropic, African background.",
}

promptneg={
    "president": "blurry, floating limbs",
    "morgana3": "blurry, water, sea",
    "island": "blurry, water, sea, buildings, city",
    "crater3": "blurry, generic, illustration, digital",
    "resignation2": "blurry, fantasy, two heads, armour, floating limbs",
    "house2": "blurry, spaceship, water, sea",
    "ship6": "sails, flagmast, flagpole",
    "ship8": "sails, flagmast, flagpole",
    "ship1": "",
    "worldend2": "blurry, floating shrubs, gravity defying",
    "hollow": "ground, floor, sky, sunlight",
    "pigs1": "burry, humans, soldiers, uniforms",
    "pigs2": "burry, humans, soldiers",
    "pigs3": "burry, humans, soldiers",
    "pigs4": "burry, humans",
    "boar1": "burry, humans, soldiers",
    "boar2": "burry, humans, soldiers",
    "lion": "extra limbs",
}


def get_prompt(promptname):
    if promptname in promptdict:
        prompt = promptdict[promptname]
    else:
        prompt = promptname
    
    if promptname in promptneg:
        neg = promptneg[promptname]
    else:
        neg = "blurry"

    return prompt, neg